# Generated by Django 5.2.5 on 2025-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='field_with_choices',
            field=models.CharField(choices=[('x', 'X'), ('y', 'Y'), ('z', 'Z')], default='x'),
        ),
    ]
