# Generated by Django 5.2.5 on 2025-09-02 07:10

import django.db.models.deletion
import django.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0002_book_field_with_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NumberFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_integer', models.PositiveIntegerField()),
                ('integer', models.IntegerField()),
                ('big_integer', models.BigIntegerField()),
                ('small_integer', models.SmallIntegerField()),
                ('float_number', models.FloatField()),
                ('decimal_number', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OtherFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('uuid', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('json_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TimeFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('wake_up_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='field_with_choices',
            field=models.CharField(choices=[('x', 'X'), ('y', 'Y'), ('z', 'Z')], default='x', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RelationFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many_to_many', models.ManyToManyField(related_name='related_books', to='octopusdash.book')),
                ('one_to_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
