# Generated by Django 5.2.5 on 2025-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0003_filefields_numberfields_otherfields_timefields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberfields',
            name='positive_integer',
            field=models.PositiveIntegerField(help_text='This field sholud only contain positive values.'),
        ),
    ]
