# Generated by Django 5.2.5 on 2025-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0004_alter_numberfields_positive_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationfields',
            name='many_to_many',
            field=models.ManyToManyField(help_text='<span> Hold <strong>CTRL+Click</strong> to select more than one relation </span>', related_name='related_books', to='octopusdash.book'),
        ),
    ]
