# Generated by Django 5.2.5 on 2025-09-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0006_prefrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefrence',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('cup', 'Cup'), ('bumblebee', 'Bumblebee'), ('emerald', 'Emerald'), ('corporate', 'Corporate'), ('synthwave', 'Synthwave'), ('retro', 'Retro'), ('cyberpunk', 'Cyberpunk'), ('valentine', 'Valentine'), ('honey', 'Honey'), ('forest', 'Forest'), ('aqua', 'Aqua'), ('lofi', 'Lofi'), ('pastel', 'Pastel'), ('fantasy', 'Fantasy'), ('wireframe', 'Wireframe'), ('black', 'Black'), ('night', 'Night'), ('coffee', 'Coffee'), ('winter', 'Winter')], default='cup', max_length=20),
        ),
    ]
