# Generated by Django 5.2.5 on 2025-09-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0007_alter_prefrence_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='relationfields',
            name='many_to_many',
        ),
        migrations.DeleteModel(
            name='FileFields',
        ),
        migrations.DeleteModel(
            name='NumberFields',
        ),
        migrations.DeleteModel(
            name='OtherFields',
        ),
        migrations.RemoveField(
            model_name='prefrence',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relationfields',
            name='one_to_one',
        ),
        migrations.DeleteModel(
            name='TimeFields',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Prefrence',
        ),
        migrations.DeleteModel(
            name='RelationFields',
        ),
    ]
