# Generated by Django 5.2.5 on 2025-09-04 07:20

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('octopusdash', '0008_remove_book_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(choices=[('a', 'Option A'), ('b', 'Option B')], max_length=50, verbose_name='CharField')),
                ('text_field', models.TextField(blank=True, verbose_name='TextField')),
                ('integer_field', models.IntegerField(default=0, verbose_name='IntegerField')),
                ('big_integer_field', models.BigIntegerField(default=0, verbose_name='BigIntegerField')),
                ('small_integer_field', models.SmallIntegerField(default=0, verbose_name='SmallIntegerField')),
                ('positive_integer_field', models.PositiveIntegerField(default=0, verbose_name='PositiveIntegerField')),
                ('positive_small_integer_field', models.PositiveSmallIntegerField(default=0, verbose_name='PositiveSmallIntegerField')),
                ('float_field', models.FloatField(default=0.0, verbose_name='FloatField')),
                ('decimal_field', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='DecimalField')),
                ('boolean_field', models.BooleanField(default=False, verbose_name='BooleanField')),
                ('null_boolean_field', models.BooleanField(null=True, verbose_name='NullBooleanField (deprecated, test only)')),
                ('date_field', models.DateField(blank=True, null=True, verbose_name='DateField')),
                ('datetime_field', models.DateTimeField(blank=True, null=True, verbose_name='DateTimeField')),
                ('time_field', models.TimeField(blank=True, null=True, verbose_name='TimeField')),
                ('duration_field', models.DurationField(blank=True, null=True, verbose_name='DurationField')),
                ('file_field', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='FileField')),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='ImageField')),
                ('slug_field', models.SlugField(unique=True, verbose_name='SlugField')),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUIDField')),
                ('email_field', models.EmailField(blank=True, max_length=100, verbose_name='EmailField')),
                ('url_field', models.URLField(blank=True, verbose_name='URLField')),
                ('ip_field', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IPAddressField')),
                ('binary_field', models.BinaryField(blank=True, null=True, verbose_name='BinaryField')),
                ('json_field', models.JSONField(blank=True, default=dict, null=True, verbose_name='JSONField')),
                ('array_field', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=5)),
                ('hstore_field', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('status_choice', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1, verbose_name='Status Choice')),
                ('foreign_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_related', to='octopusdash.allfields')),
                ('many_to_many', models.ManyToManyField(blank=True, related_name='m2m_related', to='octopusdash.allfields')),
                ('one_to_one', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oto_related', to='octopusdash.allfields')),
            ],
        ),
    ]
